const fs = require('fs');
const lines = [
  'import type { Metadata } from "next";',
  'import { Fraunces, Plus_Jakarta_Sans } from "next/font/google";',
  'import "./globals.css";',
  'import { ThemeProvider } from "@/components/theme-provider";',
  'import { TopBar } from "@/components/top-bar";',
  '',
  'const display = Fraunces({ subsets: ["latin", "vietnamese"], variable: "--font-display", display: "swap" });',
  'const sans = Plus_Jakarta_Sans({ subsets: ["latin", "vietnamese"], variable: "--font-sans", display: "swap" });',
  '',
  'export const metadata: Metadata = {',
  '  icons: { icon: "/favicon.svg" },',
  '  title: "Apple English \u2014 H\u1ecdc ti\u1ebfng Anh t\u1eeb con s\u1ed1 0",',
  '  description: "N\u1ec1n t\u1ea3ng h\u1ecdc ti\u1ebfng Anh cho ng\u01b0\u1eddi Vi\u1ec7t m\u1ea5t g\u1ed1c. L\u1ed9 tr\u00ecnh A0\u2192A2, TOEIC, v\u00e0 mini games \u0111\u1ec3 h\u1ecdc m\u1ed7i ng\u00e0y 10 ph\u00fat.",',
  '};',
  '',
  'function Footer() {',
  '  return (',
  '    <footer className="bg-white dark:bg-ink-900 border-t border-sky-100 dark:border-sky-900 mt-auto">',
  '      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12">',
  '        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 mb-10">',
  '          <div className="col-span-1 sm:col-span-2 md:col-span-1">',
  '            <div className="flex items-center gap-2 mb-3">',
  '              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-sky-400 to-blue-600 grid place-items-center shadow-md flex-shrink-0">',
  '                <svg width="22" height="22" viewBox="0 0 22 22" fill="none"><circle cx="11" cy="11" r="9" stroke="white" strokeWidth="1.5" fill="none"/><ellipse cx="11" cy="11" rx="4" ry="9" stroke="white" strokeWidth="1.2" fill="none"/><line x1="2" y1="11" x2="20" y2="11" stroke="white" strokeWidth="1.2"/><line x1="4" y1="7" x2="18" y2="7" stroke="white" strokeWidth="1"/><line x1="4" y1="15" x2="18" y2="15" stroke="white" strokeWidth="1"/><circle cx="14" cy="5" r="3.5" fill="#4ade80"/></svg>',
  '              </div>',
  '              <span className="font-display text-lg font-black"><span className="text-sky-600">Apple</span> <span className="bg-gradient-to-r from-sky-500 to-blue-600 bg-clip-text text-transparent">English</span></span>',
  '            </div>',
  '            <p className="text-sm text-ink-500 dark:text-paper-200 leading-relaxed mb-4">N\u1ec1n t\u1ea3ng h\u1ecdc ti\u1ebfng Anh mi\u1ec5n ph\u00ed cho ng\u01b0\u1eddi Vi\u1ec7t m\u1ea5t g\u1ed1c. T\u1eeb A0 l\u00ean giao ti\u1ebfp t\u1ef1 tin.</p>',
  '            <div className="flex items-center gap-2">',
  '              <span className="px-3 py-1 bg-sky-50 text-sky-600 text-xs font-bold rounded-full">\uD83C\uDDF9\uD83C\uDDFB Vi\u1ec7t Nam</span>',
  '              <span className="px-3 py-1 bg-green-50 text-green-600 text-xs font-bold rounded-full">\uD83C\uDD93 Mi\u1ec5n ph\u00ed</span>',
  '            </div>',
  '          </div>',
  '          <div>',
  '            <p className="font-black text-xs text-sky-900 dark:text-paper-50 uppercase tracking-widest mb-4">H\u1ecdc</p>',
  '            <ul className="space-y-2.5">',
  '              {[',
  '                { href: "/learn/beginner", label: "M\u1ea5t g\u1ed1c A0\u2192A2" },',
  '                { href: "/learn/toeic", label: "Luy\u1ec7n TOEIC" },',
  '                { href: "/learn/topics", label: "Ch\u1ee7 \u0111\u1ec1 th\u1ef1c t\u1ebf" },',
  '                { href: "/games", label: "Mini Games" },',
  '                { href: "/dashboard", label: "Ti\u1ebfn \u0111\u1ed9" },',
  '              ].map((item) => (',
  '                <li key={item.href}><a href={item.href} className="text-sm text-ink-500 dark:text-paper-200 hover:text-sky-600 transition-colors">{item.label}</a></li>',
  '              ))}',
  '            </ul>',
  '          </div>',
  '          <div>',
  '            <p className="font-black text-xs text-sky-900 dark:text-paper-50 uppercase tracking-widest mb-4">B\u00e0i vi\u1ebft</p>',
  '            <ul className="space-y-2.5">',
  '              {[',
  '                { href: "/blog/tai-sao-hoc-tieng-anh-mai-khong-gioi", label: "T\u1ea1i sao m\u00e3i kh\u00f4ng gi\u1ecfi?" },',
  '                { href: "/blog/toeic-450-trong-2-thang", label: "TOEIC 450 trong 2 th\u00e1ng" },',
  '                { href: "/blog/hoc-tieng-anh-qua-phim", label: "H\u1ecdc qua phim" },',
  '                { href: "/blog/30-thanh-ngu-pho-bien-tieng-anh", label: "30 th\u00e0nh ng\u1eef ph\u1ed5 bi\u1ebfn" },',
  '                { href: "/blog", label: "Xem t\u1ea5t c\u1ea3 \u2192" },',
  '              ].map((item) => (',
  '                <li key={item.href}><a href={item.href} className="text-sm text-ink-500 dark:text-paper-200 hover:text-sky-600 transition-colors">{item.label}</a></li>',
  '              ))}',
  '            </ul>',
  '          </div>',
  '          <div>',
  '            <p className="font-black text-xs text-sky-900 dark:text-paper-50 uppercase tracking-widest mb-4">Th\u00f4ng tin</p>',
  '            <ul className="space-y-2.5">',
  '              {["\uD83C\uDDFE\uD83C\uDDF3 D\u00e0nh cho ng\u01b0\u1eddi Vi\u1ec7t", "\uD83C\uDDE9\uD83C\uDDEA \u0110\u00e3 h\u1ecdc \u1edf \u0110\u1ee9c", "\uD83D\uDCDA N\u1ed9i dung ti\u1ebfng Vi\u1ec7t", "\uD83D\uDE80 C\u1eadp nh\u1eadt li\u00ean t\u1ee5c"].map((t, i) => (',
  '                <li key={i} className="text-sm text-ink-500 dark:text-paper-200">{t}</li>',
  '              ))}',
  '            </ul>',
  '          </div>',
  '        </div>',
  '        <div className="pt-6 border-t border-sky-100 dark:border-sky-900 flex flex-col sm:flex-row items-center justify-between gap-3">',
  '          <p className="text-xs text-ink-300">\u00a9 2026 Apple English. Mi\u1ec5n ph\u00ed m\u00e3i m\u00e3i \u2764\uFE0F</p>',
  '          <div className="flex items-center gap-4">',
  '            <span className="text-xs text-ink-300">Made with \u2764\uFE0F for ng\u01b0\u1eddi Vi\u1ec7t</span>',
  '            <div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div><span className="text-xs text-green-500 font-semibold">Online</span></div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </footer>',
  '  );',
  '}',
  '',
  'export default function RootLayout({ children }: { children: React.ReactNode }) {',
  '  return (',
  '    <html lang="vi" className={${display.variable} } suppressHydrationWarning>',
  '      <body className="font-sans min-h-screen flex flex-col">',
  '        <ThemeProvider>',
  '          <TopBar />',
  '          <main className="flex-1">{children}</main>',
  '          <Footer />',
  '        </ThemeProvider>',
  '      </body>',
  '    </html>',
  '  );',
  '}',
];
fs.writeFileSync('app/layout.tsx', lines.join('\n'), 'utf8');
console.log('Done:', fs.readFileSync('app/layout.tsx','utf8').includes('Footer'));
