// ──────────────────────────────────────────────────────────────────
// TOEIC Mini Test — BEGINNER LEVEL (target 400-600)
// 100 questions: 50 Listening + 50 Reading
// Time: 60 minutes
// ──────────────────────────────────────────────────────────────────

import type { ToeicQuestion } from "./toeic-types";

export const BEGINNER_QUESTIONS: ToeicQuestion[] = [
  // ─── PART 1 — Photographs (6 câu) ──────────────────────────
  {
    id: "B-P1-1", part: 1, section: "listening",
    audioText: "A. The man is reading a book. B. The man is sitting at a desk. C. The man is opening a window. D. The man is using a computer.",
    imagePrompt: "Một người đàn ông đang ngồi tại bàn, dùng laptop trong văn phòng.",
    question: "Câu nào mô tả đúng nhất bức ảnh?",
    options: [
      "A. The man is reading a book.",
      "B. The man is sitting at a desk.",
      "C. The man is opening a window.",
      "D. The man is using a computer.",
    ],
    correctIndex: 3,
    explain: "Ảnh mô tả người dùng laptop → D đúng. B cũng đúng một phần nhưng D cụ thể hơn và là câu đúng nhất.",
  },
  {
    id: "B-P1-2", part: 1, section: "listening",
    audioText: "A. People are walking on the street. B. People are eating lunch. C. People are riding bicycles. D. People are crossing the road.",
    imagePrompt: "Nhiều người đang đi bộ trên vỉa hè đông đúc.",
    question: "Câu nào mô tả đúng nhất?",
    options: ["A. People are walking on the street.", "B. People are eating lunch.", "C. People are riding bicycles.", "D. People are crossing the road."],
    correctIndex: 0,
    explain: "Vỉa hè đông người đi bộ → A đúng.",
  },
  {
    id: "B-P1-3", part: 1, section: "listening",
    audioText: "A. The woman is wearing glasses. B. The woman is holding a phone. C. The woman is drinking coffee. D. The woman is writing on paper.",
    imagePrompt: "Một phụ nữ đang cầm điện thoại, nhìn vào màn hình.",
    question: "Câu nào mô tả đúng nhất?",
    options: ["A. The woman is wearing glasses.", "B. The woman is holding a phone.", "C. The woman is drinking coffee.", "D. The woman is writing on paper."],
    correctIndex: 1,
    explain: "Hành động chính là cầm điện thoại → B.",
  },
  {
    id: "B-P1-4", part: 1, section: "listening",
    audioText: "A. The car is parked. B. The car is moving. C. The car is broken. D. The car is being washed.",
    imagePrompt: "Một chiếc xe ô tô đậu trong bãi đỗ.",
    question: "Câu nào mô tả đúng nhất?",
    options: ["A. The car is parked.", "B. The car is moving.", "C. The car is broken.", "D. The car is being washed."],
    correctIndex: 0,
    explain: "Xe đậu trong bãi → A. 'Parked' = đã đậu.",
  },
  {
    id: "B-P1-5", part: 1, section: "listening",
    audioText: "A. The children are playing in the park. B. The children are doing homework. C. The children are eating. D. The children are sleeping.",
    imagePrompt: "Trẻ em đang chạy nhảy trong công viên.",
    question: "Câu nào mô tả đúng nhất?",
    options: ["A. The children are playing in the park.", "B. The children are doing homework.", "C. The children are eating.", "D. The children are sleeping."],
    correctIndex: 0,
    explain: "Trẻ em chơi trong công viên → A.",
  },
  {
    id: "B-P1-6", part: 1, section: "listening",
    audioText: "A. The waiter is taking an order. B. The customers are paying the bill. C. The food is being cooked. D. The table is empty.",
    imagePrompt: "Người phục vụ ghi món, khách hàng ngồi ở bàn xem menu.",
    question: "Câu nào mô tả đúng nhất?",
    options: ["A. The waiter is taking an order.", "B. The customers are paying the bill.", "C. The food is being cooked.", "D. The table is empty."],
    correctIndex: 0,
    explain: "'Taking an order' = đang ghi món → A.",
  },

  // ─── PART 2 — Question-Response (19 câu, beginner làm ngắn lại) ─
  {
    id: "B-P2-1", part: 2, section: "listening",
    audioText: "Where is the meeting room? — (A) On the second floor. (B) At 3 PM. (C) Yes, it is.",
    question: "Where is the meeting room?",
    options: ["A. On the second floor.", "B. At 3 PM.", "C. Yes, it is."],
    correctIndex: 0,
    explain: "WHERE → trả lời nơi chốn. B sai (trả lời WHEN), C sai (yes/no không phù hợp).",
  },
  {
    id: "B-P2-2", part: 2, section: "listening",
    audioText: "When does the store open? — (A) On Main Street. (B) At 9 AM. (C) For two hours.",
    question: "When does the store open?",
    options: ["A. On Main Street.", "B. At 9 AM.", "C. For two hours."],
    correctIndex: 1,
    explain: "WHEN → thời gian. B đúng.",
  },
  {
    id: "B-P2-3", part: 2, section: "listening",
    audioText: "Who wrote this report? — (A) Last Monday. (B) About sales. (C) Sarah did.",
    question: "Who wrote this report?",
    options: ["A. Last Monday.", "B. About sales.", "C. Sarah did."],
    correctIndex: 2,
    explain: "WHO → người. C đúng.",
  },
  {
    id: "B-P2-4", part: 2, section: "listening",
    audioText: "How much is this jacket? — (A) It's $50. (B) Yes, please. (C) Last week.",
    question: "How much is this jacket?",
    options: ["A. It's $50.", "B. Yes, please.", "C. Last week."],
    correctIndex: 0,
    explain: "HOW MUCH → giá tiền. A đúng.",
  },
  {
    id: "B-P2-5", part: 2, section: "listening",
    audioText: "Why are you late? — (A) Because of the traffic. (B) At the office. (C) Tomorrow.",
    question: "Why are you late?",
    options: ["A. Because of the traffic.", "B. At the office.", "C. Tomorrow."],
    correctIndex: 0,
    explain: "WHY → lý do (Because...). A đúng.",
  },
  {
    id: "B-P2-6", part: 2, section: "listening",
    audioText: "Do you have a pen? — (A) No, it's mine. (B) Yes, here you go. (C) In the drawer.",
    question: "Do you have a pen?",
    options: ["A. No, it's mine.", "B. Yes, here you go.", "C. In the drawer."],
    correctIndex: 1,
    explain: "Yes/no + đưa luôn. B đúng và lịch sự.",
  },
  {
    id: "B-P2-7", part: 2, section: "listening",
    audioText: "Could you help me with this? — (A) Sure, what do you need? (B) Yesterday. (C) The blue one.",
    question: "Could you help me with this?",
    options: ["A. Sure, what do you need?", "B. Yesterday.", "C. The blue one."],
    correctIndex: 0,
    explain: "Yêu cầu giúp đỡ → đồng ý + hỏi cụ thể. A.",
  },
  {
    id: "B-P2-8", part: 2, section: "listening",
    audioText: "How was your weekend? — (A) Two days. (B) It was great, thanks. (C) Next Monday.",
    question: "How was your weekend?",
    options: ["A. Two days.", "B. It was great, thanks.", "C. Next Monday."],
    correctIndex: 1,
    explain: "Hỏi cảm nhận → trả lời cảm nhận. B.",
  },
  {
    id: "B-P2-9", part: 2, section: "listening",
    audioText: "What time is the train? — (A) On track 5. (B) About 30 minutes. (C) At 8:15.",
    question: "What time is the train?",
    options: ["A. On track 5.", "B. About 30 minutes.", "C. At 8:15."],
    correctIndex: 2,
    explain: "WHAT TIME → giờ cụ thể. C đúng.",
  },
  {
    id: "B-P2-10", part: 2, section: "listening",
    audioText: "Have you seen Mr. Brown today? — (A) Yes, this morning. (B) The brown one. (C) See you later.",
    question: "Have you seen Mr. Brown today?",
    options: ["A. Yes, this morning.", "B. The brown one.", "C. See you later."],
    correctIndex: 0,
    explain: "B là bẫy lặp âm 'brown'. A trả lời đúng câu hỏi.",
  },
  {
    id: "B-P2-11", part: 2, section: "listening",
    audioText: "Can I use your phone? — (A) The phone is ringing. (B) Of course, here you are. (C) I called yesterday.",
    question: "Can I use your phone?",
    options: ["A. The phone is ringing.", "B. Of course, here you are.", "C. I called yesterday."],
    correctIndex: 1,
    explain: "Xin phép → đồng ý. B đúng.",
  },
  {
    id: "B-P2-12", part: 2, section: "listening",
    audioText: "Where did you buy your shoes? — (A) Two days ago. (B) At the mall downtown. (C) They're black.",
    question: "Where did you buy your shoes?",
    options: ["A. Two days ago.", "B. At the mall downtown.", "C. They're black."],
    correctIndex: 1,
    explain: "WHERE → nơi. B.",
  },
  {
    id: "B-P2-13", part: 2, section: "listening",
    audioText: "Is the printer working? — (A) No, it's broken. (B) Print this page. (C) On the desk.",
    question: "Is the printer working?",
    options: ["A. No, it's broken.", "B. Print this page.", "C. On the desk."],
    correctIndex: 0,
    explain: "Yes/no + lý do. A.",
  },
  {
    id: "B-P2-14", part: 2, section: "listening",
    audioText: "Would you like some coffee? — (A) Yes, please. (B) The cafe is open. (C) I drink water.",
    question: "Would you like some coffee?",
    options: ["A. Yes, please.", "B. The cafe is open.", "C. I drink water."],
    correctIndex: 0,
    explain: "Mời → 'Yes please' / 'No thanks'. A.",
  },
  {
    id: "B-P2-15", part: 2, section: "listening",
    audioText: "What's your name? — (A) Nice to meet you. (B) I'm John Smith. (C) From Vietnam.",
    question: "What's your name?",
    options: ["A. Nice to meet you.", "B. I'm John Smith.", "C. From Vietnam."],
    correctIndex: 1,
    explain: "WHAT NAME → tên. B.",
  },
  {
    id: "B-P2-16", part: 2, section: "listening",
    audioText: "How many people are coming? — (A) About ten. (B) Tomorrow night. (C) For dinner.",
    question: "How many people are coming?",
    options: ["A. About ten.", "B. Tomorrow night.", "C. For dinner."],
    correctIndex: 0,
    explain: "HOW MANY → số lượng. A.",
  },
  {
    id: "B-P2-17", part: 2, section: "listening",
    audioText: "Did you finish the report? — (A) Yes, I sent it yesterday. (B) The reporter is here. (C) I'll start soon.",
    question: "Did you finish the report?",
    options: ["A. Yes, I sent it yesterday.", "B. The reporter is here.", "C. I'll start soon."],
    correctIndex: 0,
    explain: "Yes + thêm thông tin. A. B lặp âm 'report-er' là bẫy.",
  },
  {
    id: "B-P2-18", part: 2, section: "listening",
    audioText: "Where can I find the manager? — (A) She's in her office. (B) I manage the team. (C) Find a chair.",
    question: "Where can I find the manager?",
    options: ["A. She's in her office.", "B. I manage the team.", "C. Find a chair."],
    correctIndex: 0,
    explain: "WHERE → địa điểm. A.",
  },
  {
    id: "B-P2-19", part: 2, section: "listening",
    audioText: "What's the weather like today? — (A) I like sunny days. (B) It's raining. (C) Today is Monday.",
    question: "What's the weather like today?",
    options: ["A. I like sunny days.", "B. It's raining.", "C. Today is Monday."],
    correctIndex: 1,
    explain: "Hỏi thời tiết → mô tả thời tiết. B.",
  },

  // ─── PART 3 — Conversations (15 câu = 5 hội thoại × 3) ──────
  {
    id: "B-P3-1a", part: 3, section: "listening",
    audioText: "M: Hi, I'd like to book a table for tonight. W: Sure, for how many people? M: For four, around 7 PM.",
    conversationContext: "M (khách): Tôi muốn đặt bàn tối nay.\nW (lễ tân): Cho mấy người vậy ạ?\nM: Bốn người, khoảng 7 giờ tối.",
    question: "What is the man calling for?",
    options: ["A. To cancel a reservation.", "B. To make a reservation.", "C. To ask about the menu.", "D. To complain about service."],
    correctIndex: 1,
    explain: "'Book a table' = đặt bàn = make a reservation. B.",
  },
  {
    id: "B-P3-1b", part: 3, section: "listening",
    audioText: "M: Hi, I'd like to book a table for tonight. W: Sure, for how many people? M: For four, around 7 PM.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "How many people will be at the table?",
    options: ["A. Two.", "B. Three.", "C. Four.", "D. Seven."],
    correctIndex: 2,
    explain: "'For four' = 4 người. C. (7 PM là thời gian, không phải số người).",
  },
  {
    id: "B-P3-1c", part: 3, section: "listening",
    audioText: "M: Hi, I'd like to book a table for tonight. W: Sure, for how many people? M: For four, around 7 PM.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What time is the reservation?",
    options: ["A. 4 PM.", "B. 7 AM.", "C. 7 PM.", "D. 4 AM."],
    correctIndex: 2,
    explain: "'Around 7 PM' = khoảng 7 giờ tối. C.",
  },
  {
    id: "B-P3-2a", part: 3, section: "listening",
    audioText: "W: Excuse me, where is the post office? M: Go straight for two blocks, then turn left. It's next to the bank. W: Thank you so much.",
    conversationContext: "W (du khách): Bưu điện ở đâu vậy ạ?\nM (người địa phương): Đi thẳng 2 dãy nhà, rẽ trái. Ở cạnh ngân hàng.\nW: Cảm ơn nhiều.",
    question: "What is the woman looking for?",
    options: ["A. The bank.", "B. The post office.", "C. The supermarket.", "D. The hotel."],
    correctIndex: 1,
    explain: "Bà ấy hỏi 'where is the post office'. B.",
  },
  {
    id: "B-P3-2b", part: 3, section: "listening",
    audioText: "W: Excuse me, where is the post office? M: Go straight for two blocks, then turn left. It's next to the bank. W: Thank you so much.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "Where is the post office located?",
    options: ["A. Next to the bank.", "B. Across from the bank.", "C. Inside the bank.", "D. Behind the bank."],
    correctIndex: 0,
    explain: "'Next to the bank' = cạnh ngân hàng. A.",
  },
  {
    id: "B-P3-2c", part: 3, section: "listening",
    audioText: "W: Excuse me, where is the post office? M: Go straight for two blocks, then turn left. It's next to the bank. W: Thank you so much.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "How many blocks should she walk?",
    options: ["A. One.", "B. Two.", "C. Three.", "D. Four."],
    correctIndex: 1,
    explain: "'Two blocks'. B.",
  },
  {
    id: "B-P3-3a", part: 3, section: "listening",
    audioText: "M: I'm looking for a black shirt, size medium. W: Let me check. We have one here. Would you like to try it on? M: Yes, please.",
    conversationContext: "M (khách): Tôi tìm áo sơ mi đen, size M.\nW (nhân viên): Để tôi xem. Có một cái đây. Anh muốn thử không?\nM: Có, được không?",
    question: "Where is this conversation taking place?",
    options: ["A. At a restaurant.", "B. At a clothing store.", "C. At a library.", "D. At a hotel."],
    correctIndex: 1,
    explain: "Thử áo → cửa hàng quần áo. B.",
  },
  {
    id: "B-P3-3b", part: 3, section: "listening",
    audioText: "M: I'm looking for a black shirt, size medium. W: Let me check. We have one here. Would you like to try it on? M: Yes, please.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What color shirt does the man want?",
    options: ["A. White.", "B. Blue.", "C. Black.", "D. Red."],
    correctIndex: 2,
    explain: "'A black shirt'. C.",
  },
  {
    id: "B-P3-3c", part: 3, section: "listening",
    audioText: "M: I'm looking for a black shirt, size medium. W: Let me check. We have one here. Would you like to try it on? M: Yes, please.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What will the man do next?",
    options: ["A. Pay the bill.", "B. Leave the store.", "C. Try on the shirt.", "D. Look for another size."],
    correctIndex: 2,
    explain: "Anh ấy đồng ý thử áo. C.",
  },
  {
    id: "B-P3-4a", part: 3, section: "listening",
    audioText: "W: My computer is very slow today. M: Did you try restarting it? W: Yes, but it's still slow. M: Then I'll send someone from IT.",
    conversationContext: "W: Máy tính tôi hôm nay chạy chậm quá.\nM: Bạn đã thử khởi động lại chưa?\nW: Rồi, nhưng vẫn chậm.\nM: Vậy tôi sẽ gọi IT đến.",
    question: "What is the woman's problem?",
    options: ["A. She lost her computer.", "B. Her computer is slow.", "C. She can't find a file.", "D. The internet is down."],
    correctIndex: 1,
    explain: "'My computer is very slow'. B.",
  },
  {
    id: "B-P3-4b", part: 3, section: "listening",
    audioText: "W: My computer is very slow today. M: Did you try restarting it? W: Yes, but it's still slow. M: Then I'll send someone from IT.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What did the woman already try?",
    options: ["A. Calling IT.", "B. Buying a new computer.", "C. Restarting the computer.", "D. Reading the manual."],
    correctIndex: 2,
    explain: "Cô ấy đã 'restart' rồi. C.",
  },
  {
    id: "B-P3-4c", part: 3, section: "listening",
    audioText: "W: My computer is very slow today. M: Did you try restarting it? W: Yes, but it's still slow. M: Then I'll send someone from IT.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What will the man do?",
    options: ["A. Restart the computer.", "B. Call the IT department.", "C. Buy a new computer.", "D. Send an email."],
    correctIndex: 1,
    explain: "'I'll send someone from IT' = gọi IT đến. B.",
  },
  {
    id: "B-P3-5a", part: 3, section: "listening",
    audioText: "M: When is the next meeting? W: It's on Friday at 2 PM. M: Okay, I'll prepare the slides.",
    conversationContext: "M: Cuộc họp tiếp theo khi nào?\nW: Thứ Sáu 2 giờ chiều.\nM: OK, tôi sẽ chuẩn bị slides.",
    question: "When is the meeting?",
    options: ["A. Monday at 2 PM.", "B. Wednesday at 2 PM.", "C. Friday at 2 PM.", "D. Friday at 12 PM."],
    correctIndex: 2,
    explain: "'Friday at 2 PM'. C.",
  },
  {
    id: "B-P3-5b", part: 3, section: "listening",
    audioText: "M: When is the next meeting? W: It's on Friday at 2 PM. M: Okay, I'll prepare the slides.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What will the man prepare?",
    options: ["A. Coffee.", "B. The slides.", "C. The room.", "D. The lunch."],
    correctIndex: 1,
    explain: "'I'll prepare the slides'. B.",
  },
  {
    id: "B-P3-5c", part: 3, section: "listening",
    audioText: "M: When is the next meeting? W: It's on Friday at 2 PM. M: Okay, I'll prepare the slides.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "Where is this conversation likely taking place?",
    options: ["A. At a restaurant.", "B. At an office.", "C. At a park.", "D. At a school."],
    correctIndex: 1,
    explain: "Họp công ty + slides → văn phòng. B.",
  },

  // ─── PART 4 — Talks (10 câu = ~3-4 đoạn) ────────────────────
  {
    id: "B-P4-1a", part: 4, section: "listening",
    audioText: "Good morning passengers. This is your captain speaking. We will be landing in Tokyo in about 30 minutes. The local time is 9 AM and the weather is sunny. Please return to your seats and fasten your seatbelts. Thank you for flying with us.",
    conversationContext: "Thông báo của cơ trưởng trên máy bay.",
    question: "Who is the speaker?",
    options: ["A. A flight attendant.", "B. The captain.", "C. A tour guide.", "D. A passenger."],
    correctIndex: 1,
    explain: "'This is your captain speaking'. B.",
  },
  {
    id: "B-P4-1b", part: 4, section: "listening",
    audioText: "Good morning passengers. This is your captain speaking. We will be landing in Tokyo in about 30 minutes. The local time is 9 AM and the weather is sunny. Please return to your seats and fasten your seatbelts. Thank you for flying with us.",
    conversationContext: "(Cùng đoạn trên)",
    question: "Where is the plane landing?",
    options: ["A. Seoul.", "B. Beijing.", "C. Tokyo.", "D. Bangkok."],
    correctIndex: 2,
    explain: "'Landing in Tokyo'. C.",
  },
  {
    id: "B-P4-1c", part: 4, section: "listening",
    audioText: "Good morning passengers. This is your captain speaking. We will be landing in Tokyo in about 30 minutes. The local time is 9 AM and the weather is sunny. Please return to your seats and fasten your seatbelts. Thank you for flying with us.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What should passengers do?",
    options: ["A. Order food.", "B. Watch a movie.", "C. Fasten their seatbelts.", "D. Use the bathroom."],
    correctIndex: 2,
    explain: "'Fasten your seatbelts'. C.",
  },
  {
    id: "B-P4-2a", part: 4, section: "listening",
    audioText: "Welcome to SuperMart! This week we have a special sale. All fruits and vegetables are 20% off. Bread and milk are 10% off. The sale ends Sunday at 9 PM. Don't miss it!",
    conversationContext: "Thông báo siêu thị.",
    question: "What is the purpose of this announcement?",
    options: ["A. To announce a sale.", "B. To announce closing time.", "C. To welcome new customers.", "D. To introduce new products."],
    correctIndex: 0,
    explain: "'We have a special sale'. A.",
  },
  {
    id: "B-P4-2b", part: 4, section: "listening",
    audioText: "Welcome to SuperMart! This week we have a special sale. All fruits and vegetables are 20% off. Bread and milk are 10% off. The sale ends Sunday at 9 PM. Don't miss it!",
    conversationContext: "(Cùng đoạn trên)",
    question: "How much discount on bread?",
    options: ["A. 5%.", "B. 10%.", "C. 20%.", "D. 50%."],
    correctIndex: 1,
    explain: "'Bread and milk are 10% off'. B. (20% là cho rau quả).",
  },
  {
    id: "B-P4-2c", part: 4, section: "listening",
    audioText: "Welcome to SuperMart! This week we have a special sale. All fruits and vegetables are 20% off. Bread and milk are 10% off. The sale ends Sunday at 9 PM. Don't miss it!",
    conversationContext: "(Cùng đoạn trên)",
    question: "When does the sale end?",
    options: ["A. Friday.", "B. Saturday.", "C. Sunday.", "D. Monday."],
    correctIndex: 2,
    explain: "'Sale ends Sunday'. C.",
  },
  {
    id: "B-P4-3a", part: 4, section: "listening",
    audioText: "Hi, this is a message for Anna. This is the dentist's office calling. We need to change your appointment from Tuesday to Thursday at the same time, 3 PM. Please call us back at 555-1234 to confirm. Thank you.",
    conversationContext: "Voicemail từ phòng khám nha sĩ.",
    question: "Why is the dentist's office calling?",
    options: ["A. To cancel the appointment.", "B. To change the appointment.", "C. To remind about payment.", "D. To welcome a new patient."],
    correctIndex: 1,
    explain: "'Change your appointment'. B.",
  },
  {
    id: "B-P4-3b", part: 4, section: "listening",
    audioText: "Hi, this is a message for Anna. This is the dentist's office calling. We need to change your appointment from Tuesday to Thursday at the same time, 3 PM. Please call us back at 555-1234 to confirm. Thank you.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What is the new appointment day?",
    options: ["A. Monday.", "B. Tuesday.", "C. Wednesday.", "D. Thursday."],
    correctIndex: 3,
    explain: "'From Tuesday to Thursday'. D.",
  },
  {
    id: "B-P4-3c", part: 4, section: "listening",
    audioText: "Hi, this is a message for Anna. This is the dentist's office calling. We need to change your appointment from Tuesday to Thursday at the same time, 3 PM. Please call us back at 555-1234 to confirm. Thank you.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What should Anna do?",
    options: ["A. Visit the office today.", "B. Call back to confirm.", "C. Pay the bill.", "D. Send an email."],
    correctIndex: 1,
    explain: "'Call us back to confirm'. B.",
  },
  {
    id: "B-P4-4a", part: 4, section: "listening",
    audioText: "Attention all employees. The annual company picnic will be held this Saturday at Green Park. Lunch and drinks will be provided. Please bring your family. We hope to see you all there!",
    conversationContext: "Thông báo công ty.",
    question: "What event is being announced?",
    options: ["A. A company meeting.", "B. A training session.", "C. A company picnic.", "D. A holiday party."],
    correctIndex: 2,
    explain: "'Company picnic'. C.",
  },

  // ═══════════════════════════════════════════════════════════
  // READING SECTION (50 câu)
  // ═══════════════════════════════════════════════════════════

  // ─── PART 5 — Incomplete Sentences (20 câu) ────────────────
  {
    id: "B-P5-1", part: 5, section: "reading",
    question: "She ___ a teacher at the local school.",
    options: ["am", "is", "are", "be"],
    correctIndex: 1,
    explain: "'She' → 'is'. To be cơ bản.",
  },
  {
    id: "B-P5-2", part: 5, section: "reading",
    question: "I usually ___ coffee in the morning.",
    options: ["drinks", "drink", "drinking", "drank"],
    correctIndex: 1,
    explain: "'I' + V (present simple) → 'drink'.",
  },
  {
    id: "B-P5-3", part: 5, section: "reading",
    question: "The meeting will start ___ 3 PM.",
    options: ["in", "at", "on", "by"],
    correctIndex: 1,
    explain: "AT + giờ cụ thể.",
  },
  {
    id: "B-P5-4", part: 5, section: "reading",
    question: "There are many ___ in the office.",
    options: ["computer", "computers", "computering", "to compute"],
    correctIndex: 1,
    explain: "Sau 'many' cần danh từ số nhiều.",
  },
  {
    id: "B-P5-5", part: 5, section: "reading",
    question: "Please ___ the door before leaving.",
    options: ["close", "closes", "closed", "closing"],
    correctIndex: 0,
    explain: "Câu mệnh lệnh → V nguyên thể.",
  },
  {
    id: "B-P5-6", part: 5, section: "reading",
    question: "He doesn't ___ to work on weekends.",
    options: ["go", "goes", "going", "went"],
    correctIndex: 0,
    explain: "Sau 'doesn't' → V nguyên thể.",
  },
  {
    id: "B-P5-7", part: 5, section: "reading",
    question: "I bought ___ apple at the store.",
    options: ["a", "an", "the", "some"],
    correctIndex: 1,
    explain: "Trước nguyên âm 'a' → 'an'.",
  },
  {
    id: "B-P5-8", part: 5, section: "reading",
    question: "She lives ___ Berlin.",
    options: ["at", "on", "in", "to"],
    correctIndex: 2,
    explain: "IN + thành phố/quốc gia.",
  },
  {
    id: "B-P5-9", part: 5, section: "reading",
    question: "We ___ go to the beach last weekend.",
    options: ["don't", "doesn't", "didn't", "won't"],
    correctIndex: 2,
    explain: "Past tense → 'didn't'.",
  },
  {
    id: "B-P5-10", part: 5, section: "reading",
    question: "The book is ___ the table.",
    options: ["on", "at", "in", "by"],
    correctIndex: 0,
    explain: "ON + bề mặt.",
  },
  {
    id: "B-P5-11", part: 5, section: "reading",
    question: "Tom is ___ than his brother.",
    options: ["tall", "taller", "tallest", "more tall"],
    correctIndex: 1,
    explain: "Sau 'than' → so sánh hơn (taller).",
  },
  {
    id: "B-P5-12", part: 5, section: "reading",
    question: "I have ___ time to finish the report.",
    options: ["a few", "few", "many", "enough"],
    correctIndex: 3,
    explain: "'Enough' = đủ. 'Many' không đi với 'time' (không đếm được).",
  },
  {
    id: "B-P5-13", part: 5, section: "reading",
    question: "She is interested ___ learning Japanese.",
    options: ["at", "in", "on", "for"],
    correctIndex: 1,
    explain: "Interested IN + V-ing.",
  },
  {
    id: "B-P5-14", part: 5, section: "reading",
    question: "If it rains tomorrow, we ___ the picnic.",
    options: ["cancel", "will cancel", "cancelled", "are cancelling"],
    correctIndex: 1,
    explain: "Câu điều kiện loại 1: If + V hiện tại, S + WILL + V.",
  },
  {
    id: "B-P5-15", part: 5, section: "reading",
    question: "There ___ a lot of people at the concert.",
    options: ["is", "are", "was", "were"],
    correctIndex: 3,
    explain: "'A lot of people' (số nhiều) + past (concert đã xảy ra) → were.",
  },
  {
    id: "B-P5-16", part: 5, section: "reading",
    question: "Please send the report ___ Friday.",
    options: ["in", "at", "on", "by"],
    correctIndex: 3,
    explain: "BY + thời hạn = trước thời điểm đó.",
  },
  {
    id: "B-P5-17", part: 5, section: "reading",
    question: "She speaks English ___ than I do.",
    options: ["good", "well", "better", "best"],
    correctIndex: 2,
    explain: "So sánh hơn của 'well' → 'better'.",
  },
  {
    id: "B-P5-18", part: 5, section: "reading",
    question: "I have been working here ___ 2020.",
    options: ["for", "since", "from", "in"],
    correctIndex: 1,
    explain: "SINCE + mốc thời gian. FOR + khoảng thời gian.",
  },
  {
    id: "B-P5-19", part: 5, section: "reading",
    question: "He ___ his keys this morning.",
    options: ["loses", "lost", "losing", "is losing"],
    correctIndex: 1,
    explain: "'This morning' đã qua → past simple → lost.",
  },
  {
    id: "B-P5-20", part: 5, section: "reading",
    question: "The package will arrive ___ a few days.",
    options: ["in", "at", "on", "by"],
    correctIndex: 0,
    explain: "IN + khoảng thời gian tương lai = sau khoảng đó.",
  },

  // ─── PART 6 — Text Completion (12 câu = 3 đoạn × 4) ─────────
  {
    id: "B-P6-1a", part: 6, section: "reading",
    passage: "Dear Mr. Brown,\n\nThank you for your email. I am writing to confirm your hotel ___(1)___ for next Monday. You will stay in a deluxe room with a sea view. The room rate ___(2)___ $150 per night. Breakfast is included.\n\nPlease let us know if you ___(3)___ any special requests. We look forward ___(4)___ welcoming you.\n\nBest regards,\nThe Sunshine Hotel",
    question: "Chỗ trống (1):",
    options: ["reserve", "reservation", "reserved", "reserving"],
    correctIndex: 1,
    explain: "Sau 'hotel' cần danh từ → reservation (đặt phòng).",
  },
  {
    id: "B-P6-1b", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (2):",
    options: ["is", "are", "be", "being"],
    correctIndex: 0,
    explain: "'The room rate' (số ít) → is.",
  },
  {
    id: "B-P6-1c", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (3):",
    options: ["has", "have", "had", "having"],
    correctIndex: 1,
    explain: "'You' → have.",
  },
  {
    id: "B-P6-1d", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (4):",
    options: ["to", "for", "in", "at"],
    correctIndex: 0,
    explain: "'Look forward TO + V-ing' (cụm cố định).",
  },
  {
    id: "B-P6-2a", part: 6, section: "reading",
    passage: "Attention all staff,\n\nThe office will ___(1)___ closed next Friday for the annual cleaning. Please take your personal items home before leaving on Thursday. The cleaning team ___(2)___ start at 9 AM. We expect everything to be ___(3)___ by Monday morning.\n\nIf you have urgent work, please contact your manager ___(4)___ further instructions.\n\nThank you for your cooperation.",
    question: "Chỗ trống (1):",
    options: ["is", "be", "been", "being"],
    correctIndex: 1,
    explain: "Sau 'will' → V nguyên thể (be).",
  },
  {
    id: "B-P6-2b", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (2):",
    options: ["will", "would", "is", "are"],
    correctIndex: 0,
    explain: "Tương lai → will start.",
  },
  {
    id: "B-P6-2c", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (3):",
    options: ["ready", "readily", "readiness", "readying"],
    correctIndex: 0,
    explain: "Sau 'be' + adj → ready (sẵn sàng).",
  },
  {
    id: "B-P6-2d", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (4):",
    options: ["with", "for", "by", "in"],
    correctIndex: 1,
    explain: "'Contact someone FOR something' = liên hệ ai đó để được gì.",
  },
  {
    id: "B-P6-3a", part: 6, section: "reading",
    passage: "To our valued customers,\n\nWe are happy to ___(1)___ that our new product line is now available. The new collection includes 20 items designed ___(2)___ comfort and style.\n\nAs a thank you to our loyal customers, ___(3)___ a 15% discount this week only. Use code WELCOME15 at checkout.\n\nIf you have any questions, our customer service team is ___(4)___ help.",
    question: "Chỗ trống (1):",
    options: ["announce", "announcing", "announced", "announcement"],
    correctIndex: 0,
    explain: "'Happy to + V nguyên thể' → announce.",
  },
  {
    id: "B-P6-3b", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (2):",
    options: ["with", "for", "to", "of"],
    correctIndex: 1,
    explain: "'Designed FOR' = thiết kế cho.",
  },
  {
    id: "B-P6-3c", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (3):",
    options: ["we offer", "offering", "to offer", "offer"],
    correctIndex: 0,
    explain: "Cần chủ ngữ + động từ → 'we offer'.",
  },
  {
    id: "B-P6-3d", part: 6, section: "reading",
    passage: "(Cùng đoạn trên)",
    question: "Chỗ trống (4):",
    options: ["here for", "here to", "there for", "there to"],
    correctIndex: 1,
    explain: "'Here to + V' = có mặt để làm gì.",
  },

  // ─── PART 7 — Reading Comprehension (18 câu) ────────────────
  {
    id: "B-P7-1a", part: 7, section: "reading",
    passage: "NOTICE — Building Maintenance\n\nDear residents,\n\nWe will be performing maintenance on the water system this Saturday, November 15, from 9 AM to 3 PM. During this time, there will be NO water in the building. Please store water in advance.\n\nWe apologize for any inconvenience.\n\n— Building Management",
    question: "When will the maintenance happen?",
    options: ["A. Friday morning.", "B. Saturday from 9 AM to 3 PM.", "C. Sunday afternoon.", "D. All day Saturday."],
    correctIndex: 1,
    explain: "'Saturday, November 15, from 9 AM to 3 PM'. B.",
  },
  {
    id: "B-P7-1b", part: 7, section: "reading",
    passage: "NOTICE — Building Maintenance\n\nDear residents,\n\nWe will be performing maintenance on the water system this Saturday, November 15, from 9 AM to 3 PM. During this time, there will be NO water in the building. Please store water in advance.\n\nWe apologize for any inconvenience.\n\n— Building Management",
    question: "What should residents do?",
    options: ["A. Leave the building.", "B. Store water in advance.", "C. Call management.", "D. Pay extra fees."],
    correctIndex: 1,
    explain: "'Please store water in advance'. B.",
  },
  {
    id: "B-P7-2a", part: 7, section: "reading",
    passage: "From: sarah@company.com\nTo: huy@company.com\nSubject: Tomorrow's lunch\n\nHi Huy,\n\nWould you like to have lunch tomorrow at 12:30? I want to discuss the new project with you. There's a new Vietnamese restaurant near our office. They have great pho!\n\nLet me know if you can come.\n\nSarah",
    question: "Why is Sarah writing this email?",
    options: ["A. To cancel a meeting.", "B. To invite Huy to lunch.", "C. To recommend a restaurant.", "D. To talk about food."],
    correctIndex: 1,
    explain: "Mục đích chính: mời ăn trưa. B.",
  },
  {
    id: "B-P7-2b", part: 7, section: "reading",
    passage: "From: sarah@company.com\nTo: huy@company.com\nSubject: Tomorrow's lunch\n\nHi Huy,\n\nWould you like to have lunch tomorrow at 12:30? I want to discuss the new project with you. There's a new Vietnamese restaurant near our office. They have great pho!\n\nLet me know if you can come.\n\nSarah",
    question: "What does Sarah want to discuss?",
    options: ["A. The new project.", "B. The restaurant menu.", "C. Tomorrow's meeting.", "D. Vietnamese food."],
    correctIndex: 0,
    explain: "'Discuss the new project'. A.",
  },
  {
    id: "B-P7-2c", part: 7, section: "reading",
    passage: "From: sarah@company.com\nTo: huy@company.com\nSubject: Tomorrow's lunch\n\nHi Huy,\n\nWould you like to have lunch tomorrow at 12:30? I want to discuss the new project with you. There's a new Vietnamese restaurant near our office. They have great pho!\n\nLet me know if you can come.\n\nSarah",
    question: "What time is lunch?",
    options: ["A. 12:00.", "B. 12:30.", "C. 1:00.", "D. 1:30."],
    correctIndex: 1,
    explain: "'12:30'. B.",
  },
  {
    id: "B-P7-3a", part: 7, section: "reading",
    passage: "SUMMER SALE!\n\nGet 30% off all clothing\nGet 20% off all shoes\nGet 10% off all accessories\n\nSale runs from June 1 to June 30.\nMembers get an extra 5% off!\n\nShop online or visit our store at 123 Main Street.",
    question: "How much discount on shoes?",
    options: ["A. 10%.", "B. 20%.", "C. 30%.", "D. 50%."],
    correctIndex: 1,
    explain: "'20% off all shoes'. B.",
  },
  {
    id: "B-P7-3b", part: 7, section: "reading",
    passage: "SUMMER SALE!\n\nGet 30% off all clothing\nGet 20% off all shoes\nGet 10% off all accessories\n\nSale runs from June 1 to June 30.\nMembers get an extra 5% off!\n\nShop online or visit our store at 123 Main Street.",
    question: "When does the sale end?",
    options: ["A. May 31.", "B. June 1.", "C. June 15.", "D. June 30."],
    correctIndex: 3,
    explain: "'June 1 to June 30'. D.",
  },
  {
    id: "B-P7-3c", part: 7, section: "reading",
    passage: "SUMMER SALE!\n\nGet 30% off all clothing\nGet 20% off all shoes\nGet 10% off all accessories\n\nSale runs from June 1 to June 30.\nMembers get an extra 5% off!\n\nShop online or visit our store at 123 Main Street.",
    question: "What benefit do members get?",
    options: ["A. Free shipping.", "B. An extra 5% off.", "C. Double the discount.", "D. Free gifts."],
    correctIndex: 1,
    explain: "'Members get an extra 5% off'. B.",
  },
  {
    id: "B-P7-4a", part: 7, section: "reading",
    passage: "JOB OPENING — Marketing Assistant\n\nWe are looking for a Marketing Assistant to join our team. The successful candidate will:\n- Help create social media content\n- Reply to customer emails\n- Assist with marketing campaigns\n\nRequirements:\n- Good English (written and spoken)\n- Experience with social media\n- At least 1 year of work experience\n\nSalary: $1,500 - $2,000 per month\nSend your CV to hr@company.com",
    question: "What is the job title?",
    options: ["A. Marketing Manager.", "B. Marketing Assistant.", "C. Sales Assistant.", "D. Customer Service."],
    correctIndex: 1,
    explain: "'Marketing Assistant'. B.",
  },
  {
    id: "B-P7-4b", part: 7, section: "reading",
    passage: "JOB OPENING — Marketing Assistant\n\nWe are looking for a Marketing Assistant to join our team. The successful candidate will:\n- Help create social media content\n- Reply to customer emails\n- Assist with marketing campaigns\n\nRequirements:\n- Good English (written and spoken)\n- Experience with social media\n- At least 1 year of work experience\n\nSalary: $1,500 - $2,000 per month\nSend your CV to hr@company.com",
    question: "Which of the following is NOT a requirement?",
    options: ["A. Good English.", "B. Social media experience.", "C. A university degree.", "D. 1 year of work experience."],
    correctIndex: 2,
    explain: "Bài KHÔNG nhắc đến bằng đại học. C.",
  },
  {
    id: "B-P7-4c", part: 7, section: "reading",
    passage: "JOB OPENING — Marketing Assistant\n\nWe are looking for a Marketing Assistant to join our team. The successful candidate will:\n- Help create social media content\n- Reply to customer emails\n- Assist with marketing campaigns\n\nRequirements:\n- Good English (written and spoken)\n- Experience with social media\n- At least 1 year of work experience\n\nSalary: $1,500 - $2,000 per month\nSend your CV to hr@company.com",
    question: "How should candidates apply?",
    options: ["A. Visit the office.", "B. Call the HR department.", "C. Send a CV by email.", "D. Apply online."],
    correctIndex: 2,
    explain: "'Send your CV to hr@company.com'. C.",
  },
  {
    id: "B-P7-5a", part: 7, section: "reading",
    passage: "TRAIN SCHEDULE — Berlin to Munich\n\nTrain ICE 501: 7:00 AM → 11:30 AM (Direct)\nTrain ICE 503: 8:30 AM → 1:15 PM (1 stop in Frankfurt)\nTrain ICE 505: 10:00 AM → 2:30 PM (Direct)\nTrain ICE 507: 12:30 PM → 5:30 PM (1 stop in Leipzig)\n\nAll trains depart from Berlin Hauptbahnhof.\nTickets: 89 EUR (standard) / 149 EUR (first class)",
    question: "Which train is the fastest?",
    options: ["A. ICE 501.", "B. ICE 503.", "C. ICE 505.", "D. ICE 507."],
    correctIndex: 0,
    explain: "ICE 501: 4.5 tiếng, các tàu khác đều lâu hơn. A.",
  },
  {
    id: "B-P7-5b", part: 7, section: "reading",
    passage: "TRAIN SCHEDULE — Berlin to Munich\n\nTrain ICE 501: 7:00 AM → 11:30 AM (Direct)\nTrain ICE 503: 8:30 AM → 1:15 PM (1 stop in Frankfurt)\nTrain ICE 505: 10:00 AM → 2:30 PM (Direct)\nTrain ICE 507: 12:30 PM → 5:30 PM (1 stop in Leipzig)\n\nAll trains depart from Berlin Hauptbahnhof.\nTickets: 89 EUR (standard) / 149 EUR (first class)",
    question: "How much is a standard ticket?",
    options: ["A. 89 EUR.", "B. 149 EUR.", "C. 49 EUR.", "D. 100 EUR."],
    correctIndex: 0,
    explain: "'89 EUR (standard)'. A.",
  },
  {
    id: "B-P7-5c", part: 7, section: "reading",
    passage: "TRAIN SCHEDULE — Berlin to Munich\n\nTrain ICE 501: 7:00 AM → 11:30 AM (Direct)\nTrain ICE 503: 8:30 AM → 1:15 PM (1 stop in Frankfurt)\nTrain ICE 505: 10:00 AM → 2:30 PM (Direct)\nTrain ICE 507: 12:30 PM → 5:30 PM (1 stop in Leipzig)\n\nAll trains depart from Berlin Hauptbahnhof.\nTickets: 89 EUR (standard) / 149 EUR (first class)",
    question: "Where do trains depart from?",
    options: ["A. Munich Station.", "B. Frankfurt Station.", "C. Berlin Hauptbahnhof.", "D. Leipzig Station."],
    correctIndex: 2,
    explain: "'Depart from Berlin Hauptbahnhof'. C.",
  },
  {
    id: "B-P7-6a", part: 7, section: "reading",
    passage: "Restaurant Review:\n\nI visited Tony's Pizza last Friday with my family. The food was great — the pizza was fresh and hot. However, the service was slow. We waited 30 minutes for our order. The price was reasonable, about $15 per person.\n\nOverall, I would recommend it, but go when it's not crowded.\n\n— John D.",
    question: "What did the writer like about the restaurant?",
    options: ["A. The fast service.", "B. The food.", "C. The decoration.", "D. The location."],
    correctIndex: 1,
    explain: "'The food was great'. B.",
  },
  {
    id: "B-P7-6b", part: 7, section: "reading",
    passage: "Restaurant Review:\n\nI visited Tony's Pizza last Friday with my family. The food was great — the pizza was fresh and hot. However, the service was slow. We waited 30 minutes for our order. The price was reasonable, about $15 per person.\n\nOverall, I would recommend it, but go when it's not crowded.\n\n— John D.",
    question: "What was the problem?",
    options: ["A. The food was cold.", "B. The price was too high.", "C. The service was slow.", "D. The restaurant was closed."],
    correctIndex: 2,
    explain: "'The service was slow'. C.",
  },
  {
    id: "B-P7-6c", part: 7, section: "reading",
    passage: "Restaurant Review:\n\nI visited Tony's Pizza last Friday with my family. The food was great — the pizza was fresh and hot. However, the service was slow. We waited 30 minutes for our order. The price was reasonable, about $15 per person.\n\nOverall, I would recommend it, but go when it's not crowded.\n\n— John D.",
    question: "Would the writer recommend the restaurant?",
    options: ["A. Yes, definitely.", "B. Yes, but with conditions.", "C. No, never.", "D. He's not sure."],
    correctIndex: 1,
    explain: "'I would recommend it, BUT go when not crowded'. B (có điều kiện).",
  },
];
