import type { ToeicQuestion } from "./toeic-types";

export const INTERMEDIATE_QUESTIONS: ToeicQuestion[] = [
  // ─── PART 1 (6) ─────────────────────────────────────────────
  { id: "I-P1-1", part: 1, section: "listening",
    audioText: "A. The technicians are repairing the equipment. B. The workers are removing safety helmets. C. The equipment is being delivered. D. The workers are taking a break.",
    imagePrompt: "Hai kỹ thuật viên đội mũ bảo hộ đang sửa máy móc công nghiệp.",
    question: "Mô tả đúng nhất?",
    options: ["A. The technicians are repairing the equipment.", "B. The workers are removing safety helmets.", "C. The equipment is being delivered.", "D. The workers are taking a break."],
    correctIndex: 0, explain: "Đang sửa máy → A. B sai (đội mũ, không tháo).",
  },
  { id: "I-P1-2", part: 1, section: "listening",
    audioText: "A. Documents are being signed. B. The meeting has ended. C. People are arranging chairs. D. Files are being stacked on a desk.",
    imagePrompt: "Một xếp tài liệu cao trên bàn làm việc trong văn phòng.",
    question: "Mô tả đúng nhất?",
    options: ["A. Documents are being signed.", "B. The meeting has ended.", "C. People are arranging chairs.", "D. Files are being stacked on a desk."],
    correctIndex: 3, explain: "Tài liệu xếp chồng trên bàn → D. Không thấy người ký (A).",
  },
  { id: "I-P1-3", part: 1, section: "listening",
    audioText: "A. The shelves are being restocked. B. Customers are checking out. C. Items are displayed on shelves. D. The store is closed.",
    imagePrompt: "Kệ hàng siêu thị đầy ắp sản phẩm, không có người.",
    question: "Mô tả đúng nhất?",
    options: ["A. The shelves are being restocked.", "B. Customers are checking out.", "C. Items are displayed on shelves.", "D. The store is closed."],
    correctIndex: 2, explain: "Items trưng bày trên kệ → C. Không thấy ai restock.",
  },
  { id: "I-P1-4", part: 1, section: "listening",
    audioText: "A. The plants are being watered. B. The garden is being landscaped. C. Some flowers are in bloom. D. Trees are being cut down.",
    imagePrompt: "Vườn hoa với nhiều hoa nở rộ.",
    question: "Mô tả đúng nhất?",
    options: ["A. The plants are being watered.", "B. The garden is being landscaped.", "C. Some flowers are in bloom.", "D. Trees are being cut down."],
    correctIndex: 2, explain: "Hoa đang nở → C.",
  },
  { id: "I-P1-5", part: 1, section: "listening",
    audioText: "A. A presentation is being given. B. Audience members are leaving. C. The screen is blank. D. Chairs are being removed.",
    imagePrompt: "Người diễn giả đang thuyết trình trước khán giả với slide trên màn hình.",
    question: "Mô tả đúng nhất?",
    options: ["A. A presentation is being given.", "B. Audience members are leaving.", "C. The screen is blank.", "D. Chairs are being removed."],
    correctIndex: 0, explain: "Đang thuyết trình → A. Passive voice.",
  },
  { id: "I-P1-6", part: 1, section: "listening",
    audioText: "A. The vehicle is parked outdoors. B. The truck is being loaded. C. The driver is fueling the car. D. Cars are being washed.",
    imagePrompt: "Xe tải đang được công nhân chất hàng lên.",
    question: "Mô tả đúng nhất?",
    options: ["A. The vehicle is parked outdoors.", "B. The truck is being loaded.", "C. The driver is fueling the car.", "D. Cars are being washed."],
    correctIndex: 1, explain: "'Loaded' = chất hàng. B.",
  },

  // ─── PART 2 (19) — Tinh vi hơn ──────────────────────────────
  { id: "I-P2-1", part: 2, section: "listening",
    audioText: "Why didn't you submit the report yesterday? — (A) Because my computer crashed. (B) The report is on your desk. (C) I'll submit it tomorrow.",
    question: "Why didn't you submit the report yesterday?",
    options: ["A. Because my computer crashed.", "B. The report is on your desk.", "C. I'll submit it tomorrow."],
    correctIndex: 0, explain: "WHY + past → 'Because' + lý do quá khứ.",
  },
  { id: "I-P2-2", part: 2, section: "listening",
    audioText: "Have you reviewed the proposal yet? — (A) The proposal was approved. (B) Not yet, I'm still working on it. (C) Review the next page.",
    question: "Have you reviewed the proposal yet?",
    options: ["A. The proposal was approved.", "B. Not yet, I'm still working on it.", "C. Review the next page."],
    correctIndex: 1, explain: "'Not yet' trả lời gián tiếp + lý do.",
  },
  { id: "I-P2-3", part: 2, section: "listening",
    audioText: "Could you transfer the call to Mr. Lee? — (A) He's in a meeting right now. (B) I'll transfer some money. (C) Calls are recorded.",
    question: "Could you transfer the call to Mr. Lee?",
    options: ["A. He's in a meeting right now.", "B. I'll transfer some money.", "C. Calls are recorded."],
    correctIndex: 0, explain: "Lý do không thực hiện được. A. B bẫy lặp 'transfer'.",
  },
  { id: "I-P2-4", part: 2, section: "listening",
    audioText: "Would you prefer the morning shift or the evening shift? — (A) I work full-time. (B) The morning works better for me. (C) Yes, I prefer it.",
    question: "Would you prefer the morning shift or the evening shift?",
    options: ["A. I work full-time.", "B. The morning works better for me.", "C. Yes, I prefer it."],
    correctIndex: 1, explain: "Câu hỏi lựa chọn → chọn 1. B.",
  },
  { id: "I-P2-5", part: 2, section: "listening",
    audioText: "When will the new branch open? — (A) On the corner of 5th Avenue. (B) It depends on construction. (C) About 50 employees.",
    question: "When will the new branch open?",
    options: ["A. On the corner of 5th Avenue.", "B. It depends on construction.", "C. About 50 employees."],
    correctIndex: 1, explain: "Trả lời gián tiếp 'depends on'. B.",
  },
  { id: "I-P2-6", part: 2, section: "listening",
    audioText: "Who's in charge of the marketing campaign? — (A) The campaign starts next week. (B) Sarah is leading it. (C) Marketing is important.",
    question: "Who's in charge of the marketing campaign?",
    options: ["A. The campaign starts next week.", "B. Sarah is leading it.", "C. Marketing is important."],
    correctIndex: 1, explain: "WHO → người cụ thể. B.",
  },
  { id: "I-P2-7", part: 2, section: "listening",
    audioText: "I think we should hire more staff. — (A) The new hire is great. (B) That's a good point. (C) We staff the booth.",
    question: "I think we should hire more staff.",
    options: ["A. The new hire is great.", "B. That's a good point.", "C. We staff the booth."],
    correctIndex: 1, explain: "Statement → đáp lại bằng ý kiến. B.",
  },
  { id: "I-P2-8", part: 2, section: "listening",
    audioText: "Where did you put the contract? — (A) I signed it yesterday. (B) In the top drawer. (C) The contract is long.",
    question: "Where did you put the contract?",
    options: ["A. I signed it yesterday.", "B. In the top drawer.", "C. The contract is long."],
    correctIndex: 1, explain: "WHERE → vị trí. B.",
  },
  { id: "I-P2-9", part: 2, section: "listening",
    audioText: "How long does it take to fly to Singapore? — (A) About 6 hours. (B) I went last month. (C) The flight is delayed.",
    question: "How long does it take to fly to Singapore?",
    options: ["A. About 6 hours.", "B. I went last month.", "C. The flight is delayed."],
    correctIndex: 0, explain: "HOW LONG → thời gian. A.",
  },
  { id: "I-P2-10", part: 2, section: "listening",
    audioText: "Aren't you coming to the workshop tomorrow? — (A) I came back yesterday. (B) Actually, I can't make it. (C) The workshop is downstairs.",
    question: "Aren't you coming to the workshop tomorrow?",
    options: ["A. I came back yesterday.", "B. Actually, I can't make it.", "C. The workshop is downstairs."],
    correctIndex: 1, explain: "Negative question → 'Actually, I can't' trả lời gián tiếp. B.",
  },
  { id: "I-P2-11", part: 2, section: "listening",
    audioText: "Should I print this or email it? — (A) Just email it. (B) Yes, you should. (C) The printer is broken.",
    question: "Should I print this or email it?",
    options: ["A. Just email it.", "B. Yes, you should.", "C. The printer is broken."],
    correctIndex: 0, explain: "Or-question → chọn 1. A.",
  },
  { id: "I-P2-12", part: 2, section: "listening",
    audioText: "Did the package arrive yet? — (A) Yes, this morning. (B) Send it to my office. (C) The address is correct.",
    question: "Did the package arrive yet?",
    options: ["A. Yes, this morning.", "B. Send it to my office.", "C. The address is correct."],
    correctIndex: 0, explain: "Yes/no + thêm thông tin. A.",
  },
  { id: "I-P2-13", part: 2, section: "listening",
    audioText: "Why is the conference room booked all afternoon? — (A) Book it online. (B) There's a board meeting. (C) Afternoon is busy.",
    question: "Why is the conference room booked all afternoon?",
    options: ["A. Book it online.", "B. There's a board meeting.", "C. Afternoon is busy."],
    correctIndex: 1, explain: "WHY → lý do. B.",
  },
  { id: "I-P2-14", part: 2, section: "listening",
    audioText: "How was the client presentation? — (A) The clients were happy. (B) Present this to them. (C) Around 2 PM.",
    question: "How was the client presentation?",
    options: ["A. The clients were happy.", "B. Present this to them.", "C. Around 2 PM."],
    correctIndex: 0, explain: "Hỏi cảm nhận → trả lời cảm nhận. A.",
  },
  { id: "I-P2-15", part: 2, section: "listening",
    audioText: "Whose laptop is this? — (A) I have a new laptop. (B) It belongs to Mark. (C) Laptops are expensive.",
    question: "Whose laptop is this?",
    options: ["A. I have a new laptop.", "B. It belongs to Mark.", "C. Laptops are expensive."],
    correctIndex: 1, explain: "WHOSE → người sở hữu. B.",
  },
  { id: "I-P2-16", part: 2, section: "listening",
    audioText: "Could you forward the email to the team? — (A) I'll do it right now. (B) Email me later. (C) The team is small.",
    question: "Could you forward the email to the team?",
    options: ["A. I'll do it right now.", "B. Email me later.", "C. The team is small."],
    correctIndex: 0, explain: "Đồng ý + sẽ làm ngay. A.",
  },
  { id: "I-P2-17", part: 2, section: "listening",
    audioText: "What time does the conference start? — (A) In the main hall. (B) At 9 sharp. (C) For three days.",
    question: "What time does the conference start?",
    options: ["A. In the main hall.", "B. At 9 sharp.", "C. For three days."],
    correctIndex: 1, explain: "'9 sharp' = đúng 9 giờ. B.",
  },
  { id: "I-P2-18", part: 2, section: "listening",
    audioText: "I'm having trouble with the new software. — (A) IT can help you. (B) Software is updated. (C) Trouble is brewing.",
    question: "I'm having trouble with the new software.",
    options: ["A. IT can help you.", "B. Software is updated.", "C. Trouble is brewing."],
    correctIndex: 0, explain: "Đề xuất giải pháp. A.",
  },
  { id: "I-P2-19", part: 2, section: "listening",
    audioText: "Are you available for a quick call? — (A) I can talk now. (B) Yes, I'm available. (C) Call him later.",
    question: "Are you available for a quick call?",
    options: ["A. I can talk now.", "B. Yes, I'm available.", "C. Call him later."],
    correctIndex: 0, explain: "A và B đều OK, A cụ thể hơn → A.",
  },

  // ─── PART 3 (15) — Hội thoại phức tạp hơn ───────────────────
  { id: "I-P3-1a", part: 3, section: "listening",
    audioText: "M: I noticed our website traffic dropped 20% last month. W: That's concerning. Have you talked to the marketing team? M: Not yet. I wanted to gather data first. W: Good idea. Let me know what you find.",
    conversationContext: "M: Tôi để ý thấy traffic web giảm 20% tháng trước.\nW: Đáng lo đấy. Bạn đã nói với team marketing chưa?\nM: Chưa. Tôi muốn thu thập dữ liệu trước.\nW: Ý hay. Báo tôi khi có kết quả.",
    question: "What is the man's concern?",
    options: ["A. The team is too small.", "B. Website traffic dropped.", "C. Marketing budget is high.", "D. The website is slow."],
    correctIndex: 1, explain: "'Website traffic dropped 20%'. B.",
  },
  { id: "I-P3-1b", part: 3, section: "listening",
    audioText: "M: I noticed our website traffic dropped 20% last month. W: That's concerning. Have you talked to the marketing team? M: Not yet. I wanted to gather data first. W: Good idea. Let me know what you find.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What will the man do first?",
    options: ["A. Talk to marketing.", "B. Gather data.", "C. Build a new website.", "D. Hire more people."],
    correctIndex: 1, explain: "'Gather data first'. B.",
  },
  { id: "I-P3-1c", part: 3, section: "listening",
    audioText: "M: I noticed our website traffic dropped 20% last month. W: That's concerning. Have you talked to the marketing team? M: Not yet. I wanted to gather data first. W: Good idea. Let me know what you find.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What does the woman ask the man to do?",
    options: ["A. Talk to her later.", "B. Hire someone new.", "C. Update her on findings.", "D. Cancel the project."],
    correctIndex: 2, explain: "'Let me know what you find'. C.",
  },
  { id: "I-P3-2a", part: 3, section: "listening",
    audioText: "W: I'd like to return this jacket. M: Do you have the receipt? W: Yes, here it is. M: Unfortunately, the return policy is 14 days. This was bought 20 days ago.",
    conversationContext: "W: Tôi muốn trả lại cái áo này.\nM: Bạn có hoá đơn không?\nW: Có đây.\nM: Tiếc là chính sách đổi trả là 14 ngày. Cái này mua 20 ngày trước rồi.",
    question: "Where is this conversation happening?",
    options: ["A. At a restaurant.", "B. At a clothing store.", "C. At a bank.", "D. At a hotel."],
    correctIndex: 1, explain: "Trả áo → cửa hàng quần áo. B.",
  },
  { id: "I-P3-2b", part: 3, section: "listening",
    audioText: "W: I'd like to return this jacket. M: Do you have the receipt? W: Yes, here it is. M: Unfortunately, the return policy is 14 days. This was bought 20 days ago.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What is the problem?",
    options: ["A. The receipt is missing.", "B. The jacket is damaged.", "C. The return period has passed.", "D. The store is closed."],
    correctIndex: 2, explain: "20 ngày > 14 ngày → quá hạn. C.",
  },
  { id: "I-P3-2c", part: 3, section: "listening",
    audioText: "W: I'd like to return this jacket. M: Do you have the receipt? W: Yes, here it is. M: Unfortunately, the return policy is 14 days. This was bought 20 days ago.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What is the return policy?",
    options: ["A. 7 days.", "B. 14 days.", "C. 20 days.", "D. 30 days."],
    correctIndex: 1, explain: "'Return policy is 14 days'. B.",
  },
  { id: "I-P3-3a", part: 3, section: "listening",
    audioText: "M: The quarterly report is due Friday, right? W: Actually, it's been moved to Monday. The CEO wants us to include the latest sales numbers. M: That's good. I needed more time anyway.",
    conversationContext: "M: Báo cáo quý hạn thứ Sáu, đúng không?\nW: Thật ra dời đến thứ Hai rồi. CEO muốn bao gồm số liệu bán hàng mới nhất.\nM: Tốt. Tôi cũng cần thêm thời gian.",
    question: "When is the report now due?",
    options: ["A. Wednesday.", "B. Friday.", "C. Sunday.", "D. Monday."],
    correctIndex: 3, explain: "'Moved to Monday'. D. Lưu ý 'change of mind'.",
  },
  { id: "I-P3-3b", part: 3, section: "listening",
    audioText: "M: The quarterly report is due Friday, right? W: Actually, it's been moved to Monday. The CEO wants us to include the latest sales numbers. M: That's good. I needed more time anyway.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "Why was the deadline changed?",
    options: ["A. The CEO is unavailable.", "B. They need more sales data.", "C. The team is small.", "D. The system crashed."],
    correctIndex: 1, explain: "'Include latest sales numbers'. B.",
  },
  { id: "I-P3-3c", part: 3, section: "listening",
    audioText: "M: The quarterly report is due Friday, right? W: Actually, it's been moved to Monday. The CEO wants us to include the latest sales numbers. M: That's good. I needed more time anyway.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "How does the man feel about the change?",
    options: ["A. Frustrated.", "B. Surprised.", "C. Pleased.", "D. Confused."],
    correctIndex: 2, explain: "'That's good. I needed more time'. C.",
  },
  { id: "I-P3-4a", part: 3, section: "listening",
    audioText: "W: I'm interviewing candidates for the developer position tomorrow. M: How many candidates? W: Five in total. Three in the morning and two after lunch. M: Need any help reviewing their resumes?",
    conversationContext: "W: Mai tôi phỏng vấn ứng viên cho vị trí developer.\nM: Bao nhiêu ứng viên?\nW: Tổng 5. Ba người buổi sáng, hai sau bữa trưa.\nM: Cần giúp đọc CV họ không?",
    question: "How many candidates are there in the morning?",
    options: ["A. Two.", "B. Three.", "C. Four.", "D. Five."],
    correctIndex: 1, explain: "'Three in the morning'. B.",
  },
  { id: "I-P3-4b", part: 3, section: "listening",
    audioText: "W: I'm interviewing candidates for the developer position tomorrow. M: How many candidates? W: Five in total. Three in the morning and two after lunch. M: Need any help reviewing their resumes?",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What position is the woman hiring for?",
    options: ["A. Designer.", "B. Manager.", "C. Developer.", "D. Salesperson."],
    correctIndex: 2, explain: "'Developer position'. C.",
  },
  { id: "I-P3-4c", part: 3, section: "listening",
    audioText: "W: I'm interviewing candidates for the developer position tomorrow. M: How many candidates? W: Five in total. Three in the morning and two after lunch. M: Need any help reviewing their resumes?",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What does the man offer?",
    options: ["A. To conduct the interviews.", "B. To help review resumes.", "C. To recommend candidates.", "D. To book a meeting room."],
    correctIndex: 1, explain: "'Help reviewing resumes'. B.",
  },
  { id: "I-P3-5a", part: 3, section: "listening",
    audioText: "M: Our flight has been delayed by two hours. W: Oh no, we'll miss our connection in Frankfurt. M: I already called the airline. They'll book us on the next flight. W: That's a relief.",
    conversationContext: "M: Chuyến bay bị trễ 2 tiếng.\nW: Ôi không, mình sẽ lỡ chuyến nối ở Frankfurt mất.\nM: Tôi đã gọi hãng rồi. Họ sẽ đặt cho mình chuyến tiếp theo.\nW: May quá.",
    question: "What is the problem?",
    options: ["A. The flight is cancelled.", "B. The flight is delayed.", "C. The luggage is lost.", "D. The ticket is wrong."],
    correctIndex: 1, explain: "'Delayed by two hours'. B.",
  },
  { id: "I-P3-5b", part: 3, section: "listening",
    audioText: "M: Our flight has been delayed by two hours. W: Oh no, we'll miss our connection in Frankfurt. M: I already called the airline. They'll book us on the next flight. W: That's a relief.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "What did the man do?",
    options: ["A. Booked a hotel.", "B. Called the airline.", "C. Found another flight.", "D. Cancelled the trip."],
    correctIndex: 1, explain: "'Called the airline'. B.",
  },
  { id: "I-P3-5c", part: 3, section: "listening",
    audioText: "M: Our flight has been delayed by two hours. W: Oh no, we'll miss our connection in Frankfurt. M: I already called the airline. They'll book us on the next flight. W: That's a relief.",
    conversationContext: "(Cùng hội thoại trên)",
    question: "Where is the connection city?",
    options: ["A. Paris.", "B. London.", "C. Frankfurt.", "D. Munich."],
    correctIndex: 2, explain: "'Connection in Frankfurt'. C.",
  },

  // ─── PART 4 (10) — Talks ────────────────────────────────────
  { id: "I-P4-1a", part: 4, section: "listening",
    audioText: "Good afternoon team. I want to introduce our new project manager, Maria Chen. Maria has 8 years of experience in tech and will be leading the redesign of our customer portal. She'll be based in our New York office. Please welcome her on her first day next Monday.",
    conversationContext: "Thông báo giới thiệu thành viên mới của công ty.",
    question: "Who is being introduced?",
    options: ["A. A new CEO.", "B. A new project manager.", "C. A new client.", "D. A new investor."],
    correctIndex: 1, explain: "'New project manager, Maria Chen'. B.",
  },
  { id: "I-P4-1b", part: 4, section: "listening",
    audioText: "Good afternoon team. I want to introduce our new project manager, Maria Chen. Maria has 8 years of experience in tech and will be leading the redesign of our customer portal. She'll be based in our New York office. Please welcome her on her first day next Monday.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What will Maria work on?",
    options: ["A. Hiring new staff.", "B. Customer portal redesign.", "C. Office relocation.", "D. Marketing campaigns."],
    correctIndex: 1, explain: "'Leading the redesign of customer portal'. B.",
  },
  { id: "I-P4-1c", part: 4, section: "listening",
    audioText: "Good afternoon team. I want to introduce our new project manager, Maria Chen. Maria has 8 years of experience in tech and will be leading the redesign of our customer portal. She'll be based in our New York office. Please welcome her on her first day next Monday.",
    conversationContext: "(Cùng đoạn trên)",
    question: "When is Maria's first day?",
    options: ["A. Today.", "B. This Friday.", "C. Next Monday.", "D. Next Friday."],
    correctIndex: 2, explain: "'First day next Monday'. C.",
  },
  { id: "I-P4-2a", part: 4, section: "listening",
    audioText: "Thank you for calling Riverside Hotel. Our reservation desk is currently closed. Business hours are Monday to Friday, 8 AM to 8 PM, and weekends 9 AM to 6 PM. For urgent matters, please press 1. For directions to our hotel, press 2. To leave a message, please stay on the line.",
    conversationContext: "Tin nhắn tự động của khách sạn ngoài giờ.",
    question: "Why is the message playing?",
    options: ["A. The line is busy.", "B. The desk is closed.", "C. The hotel is fully booked.", "D. There's a technical issue."],
    correctIndex: 1, explain: "'Currently closed'. B.",
  },
  { id: "I-P4-2b", part: 4, section: "listening",
    audioText: "Thank you for calling Riverside Hotel. Our reservation desk is currently closed. Business hours are Monday to Friday, 8 AM to 8 PM, and weekends 9 AM to 6 PM. For urgent matters, please press 1. For directions to our hotel, press 2. To leave a message, please stay on the line.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What time does the desk close on weekends?",
    options: ["A. 6 PM.", "B. 8 PM.", "C. 9 PM.", "D. 10 PM."],
    correctIndex: 0, explain: "'Weekends 9 AM to 6 PM'. A.",
  },
  { id: "I-P4-2c", part: 4, section: "listening",
    audioText: "Thank you for calling Riverside Hotel. Our reservation desk is currently closed. Business hours are Monday to Friday, 8 AM to 8 PM, and weekends 9 AM to 6 PM. For urgent matters, please press 1. For directions to our hotel, press 2. To leave a message, please stay on the line.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What should a caller do for urgent matters?",
    options: ["A. Press 1.", "B. Press 2.", "C. Leave a message.", "D. Call back later."],
    correctIndex: 0, explain: "'Urgent matters, press 1'. A.",
  },
  { id: "I-P4-3a", part: 4, section: "listening",
    audioText: "Good morning everyone. I'm pleased to announce that our Q3 revenue exceeded targets by 15%. This is mainly due to strong sales in Asia. As a thank you, the company will provide a 5% bonus to all employees this month. Department managers will share more details by end of week.",
    conversationContext: "Bài thông báo kết quả quý của lãnh đạo.",
    question: "What is the main news?",
    options: ["A. New office opening.", "B. Q3 exceeded targets.", "C. Staff layoffs.", "D. Product launch."],
    correctIndex: 1, explain: "'Q3 revenue exceeded targets'. B.",
  },
  { id: "I-P4-3b", part: 4, section: "listening",
    audioText: "Good morning everyone. I'm pleased to announce that our Q3 revenue exceeded targets by 15%. This is mainly due to strong sales in Asia. As a thank you, the company will provide a 5% bonus to all employees this month. Department managers will share more details by end of week.",
    conversationContext: "(Cùng đoạn trên)",
    question: "What will employees receive?",
    options: ["A. Extra vacation days.", "B. A 5% bonus.", "C. New equipment.", "D. A salary raise."],
    correctIndex: 1, explain: "'5% bonus'. B.",
  },
  { id: "I-P4-3c", part: 4, section: "listening",
    audioText: "Good morning everyone. I'm pleased to announce that our Q3 revenue exceeded targets by 15%. This is mainly due to strong sales in Asia. As a thank you, the company will provide a 5% bonus to all employees this month. Department managers will share more details by end of week.",
    conversationContext: "(Cùng đoạn trên)",
    question: "Where were sales strongest?",
    options: ["A. Europe.", "B. Asia.", "C. America.", "D. Africa."],
    correctIndex: 1, explain: "'Strong sales in Asia'. B.",
  },
  { id: "I-P4-4a", part: 4, section: "listening",
    audioText: "Attention shoppers, the store will close in 30 minutes at 9 PM. Please bring your final purchases to the checkout counters. Tomorrow we open at 8 AM with a special sale on electronics. Thank you for shopping with us today.",
    conversationContext: "Thông báo siêu thị cuối ngày.",
    question: "When does the store close tonight?",
    options: ["A. 8 PM.", "B. 9 PM.", "C. 9:30 PM.", "D. 10 PM."],
    correctIndex: 1, explain: "'Close at 9 PM'. B.",
  },

  // ═══════════════════════════════════════════════════════════
  // READING (50)
  // ═══════════════════════════════════════════════════════════

  // ─── PART 5 (20) ────────────────────────────────────────────
  { id: "I-P5-1", part: 5, section: "reading",
    question: "The manager ___ all employees by Friday about the new policy.",
    options: ["will inform", "informs", "informed", "informing"], correctIndex: 0,
    explain: "'By Friday' (tương lai) → will inform.",
  },
  { id: "I-P5-2", part: 5, section: "reading",
    question: "Please submit your application ___ no later than December 1st.",
    options: ["of", "by", "on", "until"], correctIndex: 1,
    explain: "BY = hạn cuối. 'No later than' củng cố nghĩa này.",
  },
  { id: "I-P5-3", part: 5, section: "reading",
    question: "The company offers ___ benefits including health insurance and paid leave.",
    options: ["compete", "competing", "competitive", "competition"], correctIndex: 2,
    explain: "Trước 'benefits' (n) cần adj → competitive.",
  },
  { id: "I-P5-4", part: 5, section: "reading",
    question: "All employees are required ___ the safety training.",
    options: ["complete", "completing", "to complete", "completed"], correctIndex: 2,
    explain: "Required + TO V → to complete.",
  },
  { id: "I-P5-5", part: 5, section: "reading",
    question: "The new policy will take effect ___ January 1st.",
    options: ["in", "at", "on", "by"], correctIndex: 2,
    explain: "ON + ngày cụ thể.",
  },
  { id: "I-P5-6", part: 5, section: "reading",
    question: "Our department is responsible ___ customer support.",
    options: ["of", "for", "to", "with"], correctIndex: 1,
    explain: "Responsible FOR + N (collocation cố định).",
  },
  { id: "I-P5-7", part: 5, section: "reading",
    question: "The training session was ___ informative for all attendees.",
    options: ["high", "highly", "height", "higher"], correctIndex: 1,
    explain: "Adv bổ nghĩa cho adj → highly.",
  },
  { id: "I-P5-8", part: 5, section: "reading",
    question: "We received many ___ about the new product.",
    options: ["complain", "complained", "complaints", "complaining"], correctIndex: 2,
    explain: "Many + N số nhiều → complaints.",
  },
  { id: "I-P5-9", part: 5, section: "reading",
    question: "If you have any questions, please ___ contact me.",
    options: ["do not hesitate to", "not hesitate to", "no hesitate", "hesitate not"], correctIndex: 0,
    explain: "Cụm cố định: 'do not hesitate to + V'.",
  },
  { id: "I-P5-10", part: 5, section: "reading",
    question: "Sales have increased ___ 20% this quarter.",
    options: ["by", "on", "in", "of"], correctIndex: 0,
    explain: "Increase BY + số liệu.",
  },
  { id: "I-P5-11", part: 5, section: "reading",
    question: "The CEO ___ to attend the conference next month.",
    options: ["plan", "plans", "planning", "is planned"], correctIndex: 1,
    explain: "The CEO (số ít) → plans.",
  },
  { id: "I-P5-12", part: 5, section: "reading",
    question: "Despite the challenges, the team ___ to finish the project on time.",
    options: ["managed", "manage", "managing", "to manage"], correctIndex: 0,
    explain: "Past simple sau 'despite the challenges' (đã xảy ra).",
  },
  { id: "I-P5-13", part: 5, section: "reading",
    question: "The contract requires both parties ___ confidentiality.",
    options: ["maintain", "maintains", "to maintain", "maintaining"], correctIndex: 2,
    explain: "Require + O + TO V → to maintain.",
  },
  { id: "I-P5-14", part: 5, section: "reading",
    question: "Customers may request a refund ___ 30 days of purchase.",
    options: ["within", "between", "during", "from"], correctIndex: 0,
    explain: "WITHIN + khoảng thời gian = trong khoảng đó.",
  },
  { id: "I-P5-15", part: 5, section: "reading",
    question: "Our products are ___ used in over 50 countries.",
    options: ["wide", "widely", "wider", "widening"], correctIndex: 1,
    explain: "Adv bổ nghĩa cho 'used' (V-ed) → widely.",
  },
  { id: "I-P5-16", part: 5, section: "reading",
    question: "Please make sure ___ the documents before submitting.",
    options: ["review", "to review", "reviewing", "reviewed"], correctIndex: 1,
    explain: "Make sure + TO V → to review.",
  },
  { id: "I-P5-17", part: 5, section: "reading",
    question: "The new software is ___ easier to use than the old version.",
    options: ["much", "very", "so", "too"], correctIndex: 0,
    explain: "Much + comparative (easier). 'Very' không đi với so sánh hơn.",
  },
  { id: "I-P5-18", part: 5, section: "reading",
    question: "All packages must be ___ to ensure safe delivery.",
    options: ["pack", "packed", "packing", "packs"], correctIndex: 1,
    explain: "Must be + V-ed (passive) → packed.",
  },
  { id: "I-P5-19", part: 5, section: "reading",
    question: "The conference room ___ being renovated next week.",
    options: ["is", "will be", "was", "has been"], correctIndex: 1,
    explain: "'Next week' (tương lai) → will be.",
  },
  { id: "I-P5-20", part: 5, section: "reading",
    question: "Please find the report ___ to this email.",
    options: ["attach", "attached", "attaching", "to attach"], correctIndex: 1,
    explain: "'Please find attached' (cụm cố định trong email).",
  },

  // ─── PART 6 (12) ────────────────────────────────────────────
  { id: "I-P6-1a", part: 6, section: "reading",
    passage: "Dear Mr. Wilson,\n\nThank you for your interest in our consulting services. We have ___(1)___ your inquiry and would like to schedule a meeting next week. Our team specializes in helping companies ___(2)___ their operations.\n\nDuring the meeting, we will discuss your specific needs and ___(3)___ a customized proposal. We are ___(4)___ to working with you.\n\nBest regards,\nGlobal Consulting",
    question: "Chỗ (1):",
    options: ["receive", "received", "receiving", "receipt"], correctIndex: 1,
    explain: "Present perfect: have + V-ed → received.",
  },
  { id: "I-P6-1b", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (2):",
    options: ["improve", "improves", "improving", "improvement"], correctIndex: 0,
    explain: "Help + V nguyên thể → improve.",
  },
  { id: "I-P6-1c", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (3):",
    options: ["prepare", "prepares", "preparing", "prepared"], correctIndex: 0,
    explain: "Liệt kê với 'discuss' (V) → prepare (V).",
  },
  { id: "I-P6-1d", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (4):",
    options: ["look forward", "looking forward", "looked forward", "to look forward"], correctIndex: 1,
    explain: "'Be looking forward to + V-ing' (cụm cố định).",
  },
  { id: "I-P6-2a", part: 6, section: "reading",
    passage: "Notice to all employees:\n\nThe office cafeteria will be ___(1)___ from June 1 to June 15 for renovation. During this time, food trucks will be available in the parking lot. ___(2)___, the company will provide $10 daily vouchers for nearby restaurants.\n\nWe ___(3)___ for any inconvenience and appreciate your patience. The new cafeteria will feature ___(4)___ seating and updated equipment.",
    question: "Chỗ (1):",
    options: ["close", "closed", "closing", "closes"], correctIndex: 1,
    explain: "Will be + V-ed (passive future) → closed.",
  },
  { id: "I-P6-2b", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (2):",
    options: ["However", "Additionally", "Therefore", "Otherwise"], correctIndex: 1,
    explain: "Liệt kê thêm tiện ích → Additionally.",
  },
  { id: "I-P6-2c", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (3):",
    options: ["apologize", "apologized", "apologizing", "apology"], correctIndex: 0,
    explain: "We + V → apologize.",
  },
  { id: "I-P6-2d", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (4):",
    options: ["expand", "expanded", "expansion", "expanding"], correctIndex: 1,
    explain: "Adj trước noun 'seating' → expanded.",
  },
  { id: "I-P6-3a", part: 6, section: "reading",
    passage: "Subject: New Remote Work Policy\n\nDear Team,\n\nStarting next month, we will ___(1)___ a new hybrid work model. Employees can work from home up to 3 days per week, ___(2)___ they coordinate with their managers.\n\nThis change reflects our commitment to ___(3)___ work-life balance. Please review the updated policy document ___(4)___ to HR.",
    question: "Chỗ (1):",
    options: ["implement", "implements", "implementing", "implemented"], correctIndex: 0,
    explain: "Will + V nguyên thể → implement.",
  },
  { id: "I-P6-3b", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (2):",
    options: ["because", "although", "as long as", "in case"], correctIndex: 2,
    explain: "'As long as' = miễn là (điều kiện).",
  },
  { id: "I-P6-3c", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (3):",
    options: ["improve", "improving", "improved", "improvement"], correctIndex: 1,
    explain: "Commitment TO + V-ing → improving.",
  },
  { id: "I-P6-3d", part: 6, section: "reading",
    passage: "(Cùng đoạn)",
    question: "Chỗ (4):",
    options: ["before submitting", "before submit", "to submit", "by submit"], correctIndex: 0,
    explain: "Before + V-ing → before submitting.",
  },

  // ─── PART 7 (18) ────────────────────────────────────────────
  { id: "I-P7-1a", part: 7, section: "reading",
    passage: "MEMO\n\nTo: All Department Heads\nFrom: HR Director\nSubject: Annual Performance Reviews\n\nThe annual performance review period will begin on November 1 and end on November 30. Each manager should:\n\n1. Schedule one-on-one meetings with all direct reports\n2. Complete the standard evaluation form\n3. Submit final reviews to HR by December 5\n\nNew this year: employees will also complete a self-evaluation form before their meeting. The form is available on the HR portal.\n\nIf you have questions, please contact me directly.",
    question: "When does the review period end?",
    options: ["A. October 31.", "B. November 30.", "C. December 5.", "D. December 31."],
    correctIndex: 1, explain: "'End on November 30'. B. (December 5 là hạn nộp).",
  },
  { id: "I-P7-1b", part: 7, section: "reading",
    passage: "(Cùng memo trên)",
    question: "What is new this year?",
    options: ["A. Online meetings.", "B. Salary increases.", "C. Self-evaluation forms.", "D. More frequent reviews."],
    correctIndex: 2, explain: "'New this year: self-evaluation form'. C.",
  },
  { id: "I-P7-1c", part: 7, section: "reading",
    passage: "(Cùng memo trên)",
    question: "Where can employees find the self-evaluation form?",
    options: ["A. From their manager.", "B. On the HR portal.", "C. By email.", "D. At the HR office."],
    correctIndex: 1, explain: "'Available on the HR portal'. B.",
  },
  { id: "I-P7-2a", part: 7, section: "reading",
    passage: "PRODUCT REVIEW — Smart Coffee Maker X3\n\nI've been using the X3 for 3 months. Here's my honest review:\n\nPROS:\n- Brews coffee in 90 seconds (much faster than my old machine)\n- Mobile app works smoothly\n- Easy to clean\n\nCONS:\n- Price is high ($299)\n- Limited cup size options\n- Loud when grinding beans\n\nVERDICT: Worth it if you drink coffee daily and value time. Not recommended for occasional drinkers.\n\nRating: 4/5 stars",
    question: "How long has the reviewer used the product?",
    options: ["A. 3 weeks.", "B. 3 months.", "C. 6 months.", "D. 1 year."],
    correctIndex: 1, explain: "'3 months'. B.",
  },
  { id: "I-P7-2b", part: 7, section: "reading",
    passage: "(Cùng review trên)",
    question: "Which of the following is NOT a pro?",
    options: ["A. Fast brewing.", "B. Easy cleaning.", "C. Affordable price.", "D. Smooth app."],
    correctIndex: 2, explain: "Price là CON, không phải PRO. C.",
  },
  { id: "I-P7-2c", part: 7, section: "reading",
    passage: "(Cùng review trên)",
    question: "Who does the reviewer recommend the product to?",
    options: ["A. Occasional coffee drinkers.", "B. Daily coffee drinkers.", "C. Beginners only.", "D. Restaurants only."],
    correctIndex: 1, explain: "'Worth it if you drink coffee daily'. B.",
  },
  { id: "I-P7-3a", part: 7, section: "reading",
    passage: "JOB POSTING — Senior Sales Representative\n\nLocation: Berlin (Hybrid: 3 days office, 2 days remote)\nSalary: 55,000 - 70,000 EUR per year + commission\nExperience: 3+ years in B2B sales\n\nResponsibilities:\n- Manage 50+ existing client accounts\n- Generate new leads through networking\n- Meet quarterly sales targets\n- Travel to client sites (up to 30% of the time)\n\nWhat we offer:\n- Health insurance\n- 30 vacation days per year\n- Performance bonuses\n- Career development programs\n\nApply by sending CV to careers@company.com by August 15.",
    question: "What is the work arrangement?",
    options: ["A. Fully remote.", "B. Fully in-office.", "C. Hybrid (3 office, 2 remote).", "D. Travel only."],
    correctIndex: 2, explain: "'Hybrid: 3 days office, 2 days remote'. C.",
  },
  { id: "I-P7-3b", part: 7, section: "reading",
    passage: "(Cùng job posting)",
    question: "What is the minimum experience required?",
    options: ["A. 1 year.", "B. 2 years.", "C. 3 years.", "D. 5 years."],
    correctIndex: 2, explain: "'3+ years'. C.",
  },
  { id: "I-P7-3c", part: 7, section: "reading",
    passage: "(Cùng job posting)",
    question: "How much travel is expected?",
    options: ["A. Up to 10%.", "B. Up to 20%.", "C. Up to 30%.", "D. Up to 50%."],
    correctIndex: 2, explain: "'Up to 30%'. C.",
  },
  { id: "I-P7-3d", part: 7, section: "reading",
    passage: "(Cùng job posting)",
    question: "What is the application deadline?",
    options: ["A. August 1.", "B. August 15.", "C. August 30.", "D. September 1."],
    correctIndex: 1, explain: "'By August 15'. B.",
  },
  { id: "I-P7-4a", part: 7, section: "reading",
    passage: "EMAIL 1\nFrom: customer@email.com\nTo: support@hotel.com\nSubject: Issue with my reservation\n\nDear Support,\n\nI booked a deluxe room for 3 nights (June 10-13) but received confirmation for a standard room. Could you please check and correct this?\n\nMy booking number is HX-12345.\n\nThanks,\nLisa Park\n\n=============\n\nEMAIL 2\nFrom: support@hotel.com\nTo: customer@email.com\nSubject: Re: Issue with your reservation\n\nDear Ms. Park,\n\nWe apologize for the confusion. I've checked booking HX-12345 and confirmed your room has been upgraded to deluxe at no extra cost.\n\nYou'll find a complimentary fruit basket in your room upon arrival as our apology.\n\nBest regards,\nMike — Hotel Support",
    question: "What was Lisa's complaint?",
    options: ["A. Wrong dates booked.", "B. Wrong room type confirmed.", "C. Cancellation issue.", "D. Payment failed."],
    correctIndex: 1, explain: "'Confirmation for standard, but booked deluxe'. B.",
  },
  { id: "I-P7-4b", part: 7, section: "reading",
    passage: "(Cùng 2 emails)",
    question: "How long is her stay?",
    options: ["A. 1 night.", "B. 2 nights.", "C. 3 nights.", "D. 5 nights."],
    correctIndex: 2, explain: "'3 nights (June 10-13)'. C.",
  },
  { id: "I-P7-4c", part: 7, section: "reading",
    passage: "(Cùng 2 emails)",
    question: "What did the hotel do to resolve the issue?",
    options: ["A. Refunded her money.", "B. Upgraded her to deluxe.", "C. Cancelled her booking.", "D. Offered another date."],
    correctIndex: 1, explain: "'Upgraded to deluxe'. B.",
  },
  { id: "I-P7-4d", part: 7, section: "reading",
    passage: "(Cùng 2 emails)",
    question: "What extra gift will Lisa receive?",
    options: ["A. Free dinner.", "B. Room service.", "C. Fruit basket.", "D. Spa voucher."],
    correctIndex: 2, explain: "'Complimentary fruit basket'. C.",
  },
  { id: "I-P7-5a", part: 7, section: "reading",
    passage: "INVOICE — Bright Office Supplies\n\nInvoice #: INV-2026-0589\nDate: May 15, 2026\nDue Date: June 14, 2026 (Net 30)\n\nBilled to: TechCorp Vietnam\n\nItems:\n1. Office paper (20 boxes) — $400\n2. Pens, blue (200 units) — $80\n3. Notebooks (50 units) — $150\n4. Whiteboards (5 units) — $250\n\nSubtotal: $880\nTax (10%): $88\nTotal: $968\n\nPayment methods: Bank transfer, credit card\nLate payment: 1.5% monthly fee\n\nThank you for your business!",
    question: "When is payment due?",
    options: ["A. May 15.", "B. June 14.", "C. May 30.", "D. June 30."],
    correctIndex: 1, explain: "'Due Date: June 14'. B.",
  },
  { id: "I-P7-5b", part: 7, section: "reading",
    passage: "(Cùng invoice)",
    question: "What is the total amount?",
    options: ["A. $880.", "B. $968.", "C. $1,000.", "D. $1,088."],
    correctIndex: 1, explain: "'Total: $968' (subtotal + tax). B.",
  },
  { id: "I-P7-5c", part: 7, section: "reading",
    passage: "(Cùng invoice)",
    question: "What happens if payment is late?",
    options: ["A. Service is cancelled.", "B. 1.5% monthly fee.", "C. Account is closed.", "D. No consequence."],
    correctIndex: 1, explain: "'1.5% monthly fee'. B.",
  },
  { id: "I-P7-5d", part: 7, section: "reading",
    passage: "(Cùng invoice)",
    question: "Which item costs the most?",
    options: ["A. Office paper.", "B. Pens.", "C. Notebooks.", "D. Whiteboards."],
    correctIndex: 0, explain: "Paper $400 > Whiteboards $250 > Notebooks $150 > Pens $80. A.",
  },
];
